"""Initial migration

Revision ID: 3c80dffde061
Revises: 
Create Date: 2025-07-27 15:13:57.097672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c80dffde061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=True),
    sa.Column('data_type_patterns', sa.Text(), nullable=True),
    sa.Column('value_patterns', sa.Text(), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('pii_category', sa.String(length=100), nullable=True),
    sa.Column('compliance_tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_classifications_id'), 'data_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_data_classifications_name'), 'data_classifications', ['name'], unique=True)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('POSTGRESQL', 'MYSQL', 'BIGQUERY', 'SNOWFLAKE', 'REDSHIFT', 'S3', 'DATABRICKS', 'MONGODB', 'ORACLE', 'MSSQL', 'HIVE', 'SPARK', name='datasourcetypeenum'), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connection_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('auto_crawl_enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_schedule', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.Enum('PROD', 'STAGING', 'DEV', 'TEST', name='environment'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_index(op.f('ix_data_sources_type'), 'data_sources', ['type'], unique=False)
    op.create_index(op.f('ix_data_sources_urn'), 'data_sources', ['urn'], unique=True)
    op.create_table('quality_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_dimensions_id'), 'quality_dimensions', ['id'], unique=False)
    op.create_index(op.f('ix_quality_dimensions_name'), 'quality_dimensions', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_tag_id', sa.Integer(), nullable=True),
    sa.Column('is_system_tag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_parent_tag_id'), 'tags', ['parent_tag_id'], unique=False)
    op.create_index(op.f('ix_tags_urn'), 'tags', ['urn'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DATA_STEWARD', 'DATA_ANALYST', 'VIEWER', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'SEARCH', 'DOWNLOAD', 'EXPORT', 'TAG_ADD', 'TAG_REMOVE', 'APPROVE', 'REJECT', name='auditactionenum'), nullable=False),
    sa.Column('resource_type', sa.Enum('USER', 'TABLE', 'COLUMN', 'DATA_SOURCE', 'DOMAIN', 'TAG', 'LINEAGE_EDGE', 'BUSINESS_GLOSSARY', 'QUALITY_RULE', 'ACCESS_REQUEST', name='resourcetypeenum'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('scope_domains', sa.JSON(), nullable=True),
    sa.Column('scope_tables', sa.JSON(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_created_by'), 'compliance_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_compliance_reports_id'), 'compliance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_name'), 'compliance_reports', ['name'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('applies_to_domains', sa.JSON(), nullable=True),
    sa.Column('applies_to_tags', sa.JSON(), nullable=True),
    sa.Column('applies_to_sensitivity', sa.JSON(), nullable=True),
    sa.Column('auto_delete_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_days_before', sa.Integer(), nullable=False),
    sa.Column('regulatory_basis', sa.String(length=500), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_approved_by'), 'data_retention_policies', ['approved_by'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_name'), 'data_retention_policies', ['name'], unique=True)
    op.create_index(op.f('ix_data_retention_policies_owner_id'), 'data_retention_policies', ['owner_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('steward_id', sa.Integer(), nullable=True),
    sa.Column('environment', sa.Enum('PROD', 'STAGING', 'DEV', 'TEST', name='environment'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['steward_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_steward_id'), 'domains', ['steward_id'], unique=False)
    op.create_index(op.f('ix_domains_urn'), 'domains', ['urn'], unique=True)
    op.create_table('lineage_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('job_config', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineage_jobs_external_job_id'), 'lineage_jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_lineage_jobs_id'), 'lineage_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_lineage_jobs_name'), 'lineage_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_lineage_jobs_owner_id'), 'lineage_jobs', ['owner_id'], unique=False)
    op.create_table('quality_dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_config', sa.JSON(), nullable=True),
    sa.Column('metrics_config', sa.JSON(), nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_dashboards_id'), 'quality_dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_quality_dashboards_name'), 'quality_dashboards', ['name'], unique=False)
    op.create_index(op.f('ix_quality_dashboards_owner_id'), 'quality_dashboards', ['owner_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('business_glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('business_definition', sa.Text(), nullable=True),
    sa.Column('technical_definition', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('acronyms', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_glossary_approved_by'), 'business_glossary', ['approved_by'], unique=False)
    op.create_index(op.f('ix_business_glossary_category'), 'business_glossary', ['category'], unique=False)
    op.create_index(op.f('ix_business_glossary_domain_id'), 'business_glossary', ['domain_id'], unique=False)
    op.create_index(op.f('ix_business_glossary_id'), 'business_glossary', ['id'], unique=False)
    op.create_index(op.f('ix_business_glossary_owner_id'), 'business_glossary', ['owner_id'], unique=False)
    op.create_index(op.f('ix_business_glossary_term'), 'business_glossary', ['term'], unique=True)
    op.create_table('lineage_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tables_processed', sa.Integer(), nullable=False),
    sa.Column('lineage_edges_created', sa.Integer(), nullable=False),
    sa.Column('lineage_edges_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['lineage_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'run_id', name='unique_job_run')
    )
    op.create_index('idx_job_run_status', 'lineage_job_runs', ['job_id', 'status', 'started_at'], unique=False)
    op.create_index(op.f('ix_lineage_job_runs_id'), 'lineage_job_runs', ['id'], unique=False)
    op.create_index(op.f('ix_lineage_job_runs_job_id'), 'lineage_job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_lineage_job_runs_run_id'), 'lineage_job_runs', ['run_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('sensitivity_level', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivitylevelenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('certification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_schema_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'schema_name', 'name', name='unique_table_per_source_schema')
    )
    op.create_index('idx_table_search', 'tables', ['name', 'description'], unique=False)
    op.create_index(op.f('ix_tables_data_source_id'), 'tables', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_tables_domain_id'), 'tables', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.create_index(op.f('ix_tables_name'), 'tables', ['name'], unique=False)
    op.create_index(op.f('ix_tables_owner_id'), 'tables', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tables_schema_name'), 'tables', ['schema_name'], unique=False)
    op.create_index(op.f('ix_tables_urn'), 'tables', ['urn'], unique=True)
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('requested_access_level', sa.String(length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='accessrequeststatusenum'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_approved_by'), 'access_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_access_requests_id'), 'access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_index(op.f('ix_access_requests_table_id'), 'access_requests', ['table_id'], unique=False)
    op.create_index(op.f('ix_access_requests_user_id'), 'access_requests', ['user_id'], unique=False)
    op.create_table('columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(length=500), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_level', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivitylevelenum'), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='unique_column_per_table')
    )
    op.create_index('idx_column_pii', 'columns', ['is_pii'], unique=False)
    op.create_index('idx_column_search', 'columns', ['name', 'description'], unique=False)
    op.create_index(op.f('ix_columns_id'), 'columns', ['id'], unique=False)
    op.create_index(op.f('ix_columns_name'), 'columns', ['name'], unique=False)
    op.create_index(op.f('ix_columns_table_id'), 'columns', ['table_id'], unique=False)
    op.create_index(op.f('ix_columns_urn'), 'columns', ['urn'], unique=True)
    op.create_table('lineage_impact_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('upstream_table_count', sa.Integer(), nullable=False),
    sa.Column('upstream_column_count', sa.Integer(), nullable=False),
    sa.Column('max_upstream_depth', sa.Integer(), nullable=False),
    sa.Column('downstream_table_count', sa.Integer(), nullable=False),
    sa.Column('downstream_column_count', sa.Integer(), nullable=False),
    sa.Column('max_downstream_depth', sa.Integer(), nullable=False),
    sa.Column('is_critical_path', sa.Boolean(), nullable=False),
    sa.Column('criticality_score', sa.Integer(), nullable=False),
    sa.Column('impact_radius', sa.Integer(), nullable=False),
    sa.Column('upstream_tables', sa.JSON(), nullable=True),
    sa.Column('downstream_tables', sa.JSON(), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineage_impact_analysis_id'), 'lineage_impact_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_lineage_impact_analysis_table_id'), 'lineage_impact_analysis', ['table_id'], unique=True)
    op.create_table('table_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.Column('null_count', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_count', sa.BigInteger(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('query_count_last_30d', sa.Integer(), nullable=False),
    sa.Column('unique_users_last_30d', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_stats_id'), 'table_stats', ['id'], unique=False)
    op.create_index(op.f('ix_table_stats_table_id'), 'table_stats', ['table_id'], unique=True)
    op.create_table('table_tags',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_auto_tagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('table_id', 'tag_id')
    )
    op.create_index(op.f('ix_table_tags_created_by'), 'table_tags', ['created_by'], unique=False)
    op.create_index(op.f('ix_table_tags_table_id'), 'table_tags', ['table_id'], unique=False)
    op.create_index(op.f('ix_table_tags_tag_id'), 'table_tags', ['tag_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'table_id')
    )
    op.create_index(op.f('ix_user_favorites_table_id'), 'user_favorites', ['table_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('column_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('null_count', sa.BigInteger(), nullable=True),
    sa.Column('unique_count', sa.BigInteger(), nullable=True),
    sa.Column('min_value', sa.String(length=500), nullable=True),
    sa.Column('max_value', sa.String(length=500), nullable=True),
    sa.Column('avg_length', sa.Integer(), nullable=True),
    sa.Column('top_values', sa.JSON(), nullable=True),
    sa.Column('data_patterns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_stats_column_id'), 'column_stats', ['column_id'], unique=True)
    op.create_index(op.f('ix_column_stats_id'), 'column_stats', ['id'], unique=False)
    op.create_table('column_tags',
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_auto_tagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('column_id', 'tag_id')
    )
    op.create_index(op.f('ix_column_tags_column_id'), 'column_tags', ['column_id'], unique=False)
    op.create_index(op.f('ix_column_tags_created_by'), 'column_tags', ['created_by'], unique=False)
    op.create_index(op.f('ix_column_tags_tag_id'), 'column_tags', ['tag_id'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_table_id', sa.Integer(), nullable=True),
    sa.Column('source_column_id', sa.Integer(), nullable=True),
    sa.Column('target_table_id', sa.Integer(), nullable=True),
    sa.Column('target_column_id', sa.Integer(), nullable=True),
    sa.Column('lineage_type', sa.Enum('TABLE_TO_TABLE', 'COLUMN_TO_COLUMN', 'TABLE_TO_COLUMN', 'COLUMN_TO_TABLE', name='lineagetypeenum'), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'QUERY_LOG', 'ETL_METADATA', 'API_REPORTED', 'INFERRED', name='lineagesourceenum'), nullable=False),
    sa.Column('transformation_logic', sa.Text(), nullable=True),
    sa.Column('transformation_type', sa.String(length=100), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['lineage_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['source_table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['target_column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lineage_source', 'lineage_edges', ['source_table_id', 'source_column_id'], unique=False)
    op.create_index('idx_lineage_target', 'lineage_edges', ['target_table_id', 'target_column_id'], unique=False)
    op.create_index('idx_lineage_type', 'lineage_edges', ['lineage_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_lineage_edges_id'), 'lineage_edges', ['id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_job_id'), 'lineage_edges', ['job_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_lineage_type'), 'lineage_edges', ['lineage_type'], unique=False)
    op.create_index(op.f('ix_lineage_edges_source_column_id'), 'lineage_edges', ['source_column_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_source_table_id'), 'lineage_edges', ['source_table_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_target_column_id'), 'lineage_edges', ['target_column_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_target_table_id'), 'lineage_edges', ['target_table_id'], unique=False)
    op.create_table('quality_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('column_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.Enum('NULL_CHECK', 'UNIQUE_CHECK', 'RANGE_CHECK', 'FORMAT_CHECK', 'REFERENCE_CHECK', 'CUSTOM_SQL', 'ROW_COUNT', 'FRESHNESS', 'COMPLETENESS', 'CONSISTENCY', name='qualityruletypeenum'), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=False),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevelenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('check_frequency', sa.String(length=100), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_rules_column_id'), 'quality_rules', ['column_id'], unique=False)
    op.create_index(op.f('ix_quality_rules_created_by'), 'quality_rules', ['created_by'], unique=False)
    op.create_index(op.f('ix_quality_rules_id'), 'quality_rules', ['id'], unique=False)
    op.create_index(op.f('ix_quality_rules_name'), 'quality_rules', ['name'], unique=False)
    op.create_index(op.f('ix_quality_rules_owner_id'), 'quality_rules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_quality_rules_rule_type'), 'quality_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_quality_rules_table_id'), 'quality_rules', ['table_id'], unique=False)
    op.create_table('quality_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'WARNING', 'ERROR', 'SKIPPED', name='qualitystatusenum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('measured_value', sa.String(length=1000), nullable=True),
    sa.Column('expected_value', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('sample_failures', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['quality_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_check', 'quality_results', ['check_id', 'rule_id'], unique=False)
    op.create_index('idx_quality_rule_status', 'quality_results', ['rule_id', 'status', 'started_at'], unique=False)
    op.create_index(op.f('ix_quality_results_check_id'), 'quality_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_quality_results_id'), 'quality_results', ['id'], unique=False)
    op.create_index(op.f('ix_quality_results_rule_id'), 'quality_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_quality_results_status'), 'quality_results', ['status'], unique=False)
    op.create_table('quality_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevelenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['quality_results.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['quality_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_alerts_id'), 'quality_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_quality_alerts_result_id'), 'quality_alerts', ['result_id'], unique=False)
    op.create_index(op.f('ix_quality_alerts_rule_id'), 'quality_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_quality_alerts_severity'), 'quality_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_alerts_severity'), table_name='quality_alerts')
    op.drop_index(op.f('ix_quality_alerts_rule_id'), table_name='quality_alerts')
    op.drop_index(op.f('ix_quality_alerts_result_id'), table_name='quality_alerts')
    op.drop_index(op.f('ix_quality_alerts_id'), table_name='quality_alerts')
    op.drop_table('quality_alerts')
    op.drop_index(op.f('ix_quality_results_status'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_rule_id'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_id'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_check_id'), table_name='quality_results')
    op.drop_index('idx_quality_rule_status', table_name='quality_results')
    op.drop_index('idx_quality_check', table_name='quality_results')
    op.drop_table('quality_results')
    op.drop_index(op.f('ix_quality_rules_table_id'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_rule_type'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_owner_id'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_name'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_id'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_created_by'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_column_id'), table_name='quality_rules')
    op.drop_table('quality_rules')
    op.drop_index(op.f('ix_lineage_edges_target_table_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_target_column_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_source_table_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_source_column_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_lineage_type'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_job_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_id'), table_name='lineage_edges')
    op.drop_index('idx_lineage_type', table_name='lineage_edges')
    op.drop_index('idx_lineage_target', table_name='lineage_edges')
    op.drop_index('idx_lineage_source', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index(op.f('ix_column_tags_tag_id'), table_name='column_tags')
    op.drop_index(op.f('ix_column_tags_created_by'), table_name='column_tags')
    op.drop_index(op.f('ix_column_tags_column_id'), table_name='column_tags')
    op.drop_table('column_tags')
    op.drop_index(op.f('ix_column_stats_id'), table_name='column_stats')
    op.drop_index(op.f('ix_column_stats_column_id'), table_name='column_stats')
    op.drop_table('column_stats')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_table_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_table_tags_tag_id'), table_name='table_tags')
    op.drop_index(op.f('ix_table_tags_table_id'), table_name='table_tags')
    op.drop_index(op.f('ix_table_tags_created_by'), table_name='table_tags')
    op.drop_table('table_tags')
    op.drop_index(op.f('ix_table_stats_table_id'), table_name='table_stats')
    op.drop_index(op.f('ix_table_stats_id'), table_name='table_stats')
    op.drop_table('table_stats')
    op.drop_index(op.f('ix_lineage_impact_analysis_table_id'), table_name='lineage_impact_analysis')
    op.drop_index(op.f('ix_lineage_impact_analysis_id'), table_name='lineage_impact_analysis')
    op.drop_table('lineage_impact_analysis')
    op.drop_index(op.f('ix_columns_urn'), table_name='columns')
    op.drop_index(op.f('ix_columns_table_id'), table_name='columns')
    op.drop_index(op.f('ix_columns_name'), table_name='columns')
    op.drop_index(op.f('ix_columns_id'), table_name='columns')
    op.drop_index('idx_column_search', table_name='columns')
    op.drop_index('idx_column_pii', table_name='columns')
    op.drop_table('columns')
    op.drop_index(op.f('ix_access_requests_user_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_table_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_approved_by'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_tables_urn'), table_name='tables')
    op.drop_index(op.f('ix_tables_schema_name'), table_name='tables')
    op.drop_index(op.f('ix_tables_owner_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_name'), table_name='tables')
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_domain_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_data_source_id'), table_name='tables')
    op.drop_index('idx_table_search', table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_lineage_job_runs_run_id'), table_name='lineage_job_runs')
    op.drop_index(op.f('ix_lineage_job_runs_job_id'), table_name='lineage_job_runs')
    op.drop_index(op.f('ix_lineage_job_runs_id'), table_name='lineage_job_runs')
    op.drop_index('idx_job_run_status', table_name='lineage_job_runs')
    op.drop_table('lineage_job_runs')
    op.drop_index(op.f('ix_business_glossary_term'), table_name='business_glossary')
    op.drop_index(op.f('ix_business_glossary_owner_id'), table_name='business_glossary')
    op.drop_index(op.f('ix_business_glossary_id'), table_name='business_glossary')
    op.drop_index(op.f('ix_business_glossary_domain_id'), table_name='business_glossary')
    op.drop_index(op.f('ix_business_glossary_category'), table_name='business_glossary')
    op.drop_index(op.f('ix_business_glossary_approved_by'), table_name='business_glossary')
    op.drop_table('business_glossary')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_quality_dashboards_owner_id'), table_name='quality_dashboards')
    op.drop_index(op.f('ix_quality_dashboards_name'), table_name='quality_dashboards')
    op.drop_index(op.f('ix_quality_dashboards_id'), table_name='quality_dashboards')
    op.drop_table('quality_dashboards')
    op.drop_index(op.f('ix_lineage_jobs_owner_id'), table_name='lineage_jobs')
    op.drop_index(op.f('ix_lineage_jobs_name'), table_name='lineage_jobs')
    op.drop_index(op.f('ix_lineage_jobs_id'), table_name='lineage_jobs')
    op.drop_index(op.f('ix_lineage_jobs_external_job_id'), table_name='lineage_jobs')
    op.drop_table('lineage_jobs')
    op.drop_index(op.f('ix_domains_urn'), table_name='domains')
    op.drop_index(op.f('ix_domains_steward_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_data_retention_policies_owner_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_name'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_approved_by'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_compliance_reports_name'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_created_by'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_urn'), table_name='tags')
    op.drop_index(op.f('ix_tags_parent_tag_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_quality_dimensions_name'), table_name='quality_dimensions')
    op.drop_index(op.f('ix_quality_dimensions_id'), table_name='quality_dimensions')
    op.drop_table('quality_dimensions')
    op.drop_index(op.f('ix_data_sources_urn'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_data_classifications_name'), table_name='data_classifications')
    op.drop_index(op.f('ix_data_classifications_id'), table_name='data_classifications')
    op.drop_table('data_classifications')
    # ### end Alembic commands ###